name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]  # Adjust this to the versions you want to support

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Check Formatting
      run: npm run format-check  # Add a script in your package.json to check formatting

    - name: Build
      run: npm run build --if-present

    - name: Run Tests
      run: npm test

    - name: Generate Documentation
      run: npm run docs  # Optional: generate docs if your project requires it
